spring.application.name=sprintflow-api
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/sprintflow?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=${SPRINTFLOW_DB_USERNAME:root}
spring.datasource.password=${SPRINTFLOW_DB_PASSWORD:Hello@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

sprintflow.jwt.secret=${SPRINTFLOW_JWT_SECRET:VGhpc0lzQVN0cm9uZ0xvY2FsRGV2ZWxvcG1lbnRTZWNyZXRLZXlGb3JTcHJpbnRGbG93MjAyNg==}
sprintflow.jwt.expiration-seconds=28800
sprintflow.notification-service.url=http://localhost:8081

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
server.error.include-message=never
server.error.include-stacktrace=never
logging.level.org.hibernate.SQL=INFO
